# Generated by Django 3.0.8 on 2020-08-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mscraps',
            field=models.ManyToManyField(related_name='mscrap_users', to='two.Mission'),
        ),
        migrations.AddField(
            model_name='user',
            name='pscraps',
            field=models.ManyToManyField(related_name='pscrap_users', to='two.Photoshop'),
        ),
    ]
