# Generated by Django 2.2.7 on 2020-07-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photoshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.CharField(choices=[('핸드폰', 'phone'), ('카메라', 'camera'), ('필름카메라', 'filmcamera')], max_length=7)),
                ('color', models.CharField(choices=[('비비드한', 'vivid'), ('모노톤', 'mono'), ('빈티지한', 'Vintage')], max_length=8)),
                ('kind', models.CharField(choices=[('셀카', 'selfic'), ('풍경', 'scenery'), ('음식', 'food'), ('코디', 'style')], max_length=7)),
                ('method', models.CharField(choices=[('어플', 'apps'), ('기본카메라', 'basic')], max_length=8)),
                ('fix', models.CharField(choices=[('얼굴', 'face'), ('색감', 'color')], max_length=8)),
                ('app', models.CharField(max_length=10)),
                ('photobefore', models.ImageField(upload_to='')),
                ('photoafter', models.ImageField(upload_to='')),
                ('explain', models.TextField()),
            ],
        ),
    ]
