# Generated by Django 2.2.7 on 2020-07-27 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='ask/profile_pic')),
                ('photo', models.ImageField(blank=True, upload_to='ask')),
                ('body', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('writer', models.CharField(max_length=2)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='image')),
                ('point', models.IntegerField(default=0)),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Photoshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.CharField(choices=[('핸드폰', 'phone'), ('카메라', 'camera'), ('필름카메라', 'filmcamera')], max_length=7)),
                ('color', models.CharField(choices=[('비비드한', 'vivid'), ('모노톤', 'mono'), ('빈티지한', 'Vintage')], max_length=8)),
                ('kind', models.CharField(choices=[('셀카', 'selfic'), ('풍경', 'scenery'), ('음식', 'food'), ('코디', 'style')], max_length=7)),
                ('method', models.CharField(choices=[('어플', 'apps'), ('기본카메라', 'basic')], max_length=8)),
                ('fix', models.CharField(choices=[('얼굴', 'face'), ('색감', 'color')], max_length=8)),
                ('app', models.CharField(max_length=10)),
                ('photobefore', models.ImageField(upload_to='image/')),
                ('photoafter', models.ImageField(upload_to='image/')),
                ('explain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MissionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=2)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='image')),
                ('isPicked', models.BooleanField(default=False)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='two.Mission')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('photoshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='two.Photoshop')),
            ],
        ),
    ]
