# Generated by Django 2.2.7 on 2020-07-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoshop',
            name='device',
            field=models.CharField(choices=[('phone', '핸드폰'), ('카메라', 'camera'), ('필름카메라', 'filmcamera')], max_length=7),
        ),
    ]
