# Generated by Django 3.0.8 on 2020-08-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='pick',
            field=models.BooleanField(default=False),
        ),
    ]
