# Generated by Django 3.0.8 on 2020-08-05 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('two', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='like',
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_like',
            field=models.ManyToManyField(related_name='contest_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
