# Generated by Django 3.0.8 on 2020-07-27 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('two', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missioncomment',
            name='likers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
