# Generated by Django 2.2.7 on 2020-07-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoshop',
            name='title',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
