# Generated by Django 2.2.7 on 2020-07-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0002_auto_20200727_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoshop',
            name='device',
            field=models.CharField(choices=[('핸드폰', 'phone'), ('카메라', 'camera'), ('필름카메라', 'filmcamera')], max_length=7),
        ),
    ]
