# Generated by Django 3.0.8 on 2020-08-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0002_mission_pick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='pick',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
