# Generated by Django 3.0.8 on 2020-08-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0003_auto_20200804_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='pick',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
