# Generated by Django 3.0.8 on 2020-07-27 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0005_auto_20200727_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('writer', models.CharField(max_length=2)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='image')),
                ('point', models.IntegerField(default=0)),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MissionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=2)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='image')),
                ('isPicked', models.BooleanField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='two.Mission')),
            ],
        ),
    ]
