# Generated by Django 3.0.8 on 2020-07-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0007_auto_20200727_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='writer',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='missioncomment',
            name='writer',
            field=models.CharField(max_length=2),
        ),
    ]
