# Generated by Django 3.0.8 on 2020-07-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0008_auto_20200727_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missioncomment',
            name='isPicked',
            field=models.BooleanField(default=False),
        ),
    ]
